/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class LatteCSSLanguage extends AbstractXtextLanguage{

	public static final LatteCSSLanguage INSTANCE = new LatteCSSLanguage();

	private LatteCSSLanguage() {
		super("io.lattekit.dsl.LatteCSS");
	}

}
