/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class LatteCSSFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(LatteCSSFileType.INSTANCE, AbstractLatteCSSFileType.DEFAULT_EXTENSION);
	}

}
