/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;

public class LatteCSSCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public LatteCSSCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(LatteCSSLanguage.INSTANCE, psiModificationTracker);
	}

}
