/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class LatteCssUiModule extends AbstractLatteCssUiModule {
}
