/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.idea.completion

import io.lattekit.dsl.css.idea.lang.LatteCssLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class LatteCssCompletionContributor extends AbstractLatteCssCompletionContributor {
	new() {
		this(LatteCssLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
