/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.highlighting;

import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;

public class LatteCSSSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public LatteCSSSemanticHighlightVisitor() {
		LatteCSSLanguage.INSTANCE.injectMembers(this);
	}
}
