/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.highlighting;

import com.intellij.openapi.fileTypes.SingleLazyInstanceSyntaxHighlighterFactory;
import com.intellij.openapi.fileTypes.SyntaxHighlighter;
import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.jetbrains.annotations.NotNull;

public class LatteCSSSyntaxHighlighterFactory extends SingleLazyInstanceSyntaxHighlighterFactory {
	
	@Override
    @NotNull
    protected SyntaxHighlighter createHighlighter() {
        return LatteCSSLanguage.INSTANCE.getInstance(SyntaxHighlighter.class);
    }
}
