/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.highlighting;

import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;

public class LatteCSSBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public LatteCSSBaseColorSettingsPage() {
		LatteCSSLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return LatteCSSLanguage.INSTANCE.getDisplayName();
	}
}
