/*
 * generated by Xtext
 */
package io.lattekit.dsl.layout.ui.contentassist

import io.lattekit.dsl.layout.ui.contentassist.AbstractLayoutProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LayoutProposalProvider extends AbstractLayoutProposalProvider {
}
