/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.facet;

import com.intellij.facet.Facet;
import com.intellij.facet.FacetTypeId;
import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.eclipse.xtext.idea.facet.AbstractFacetType;

public class LatteCSSFacetType extends AbstractFacetType<LatteCSSFacetConfiguration> {

	public static final FacetTypeId<Facet<LatteCSSFacetConfiguration>> TYPEID = new FacetTypeId<Facet<LatteCSSFacetConfiguration>>("io.lattekit.dsl.LatteCSS");

	public LatteCSSFacetType() {
		super(TYPEID, "io.lattekit.dsl.LatteCSS", "LatteCSS");
		LatteCSSLanguage.INSTANCE.injectMembers(this);
	}
}
