/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
class LatteCssOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
