/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.tests

import com.google.inject.Inject
import io.lattekit.dsl.css.latteCss.CSS
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(LatteCssInjectorProvider)
class LatteCssParsingTest{

	@Inject
	ParseHelper<CSS> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
