/*
 * generated by Xtext
 */
package io.lattekit.dsl.layout.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LayoutUiModule extends io.lattekit.dsl.layout.ui.AbstractLayoutUiModule {
	public LayoutUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
