/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.idea.lang


class LatteCssFileType extends AbstractLatteCssFileType {
	public static final LatteCssFileType INSTANCE = new LatteCssFileType()
	
	new() {
		super(LatteCssLanguage.INSTANCE)
	}
}
