/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class LatteCssIdeaModule extends AbstractLatteCssIdeaModule {
}
