/*
 * generated by Xtext 2.9.0
 */
package io.lattekit.dsl.css.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class LatteCssIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new LatteCssStandaloneSetupIdea().createInjector
	}

}
