/*
 * generated by Xtext
 */
package io.lattekit.dsl.ui.contentassist

import io.lattekit.dsl.ui.contentassist.AbstractLatteCSSProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LatteCSSProposalProvider extends AbstractLatteCSSProposalProvider {
}
