/*
 * generated by Xtext
 */
package io.lattekit.dsl.layout;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LayoutStandaloneSetup extends LayoutStandaloneSetupGenerated{

	public static void doSetup() {
		new LayoutStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

