/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.ASTNode;
import com.intellij.psi.FileViewProvider;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;
import com.intellij.psi.tree.IElementType;
import io.lattekit.dsl.idea.lang.LatteCSSElementTypeProvider;
import io.lattekit.dsl.idea.lang.psi.impl.LatteCSSFileImpl;
import org.eclipse.xtext.idea.parser.AbstractXtextParserDefinition;

public class LatteCSSParserDefinition extends AbstractXtextParserDefinition {

	@Inject 
	private LatteCSSElementTypeProvider elementTypeProvider;

	@Override
	public PsiFile createFile(FileViewProvider viewProvider) {
		return new LatteCSSFileImpl(viewProvider);
	}

	@Override
	@SuppressWarnings("rawtypes")
	public PsiElement createElement(ASTNode node) {
		IElementType elementType = node.getElementType();
		return super.createElement(node);
	}

}
