/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import io.lattekit.dsl.idea.lang.LatteCSSElementTypeProvider;
import io.lattekit.dsl.idea.parser.antlr.internal.PsiInternalLatteCSSParser;
import io.lattekit.dsl.services.LatteCSSGrammarAccess;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;

public class LatteCSSPsiParser extends AbstractXtextPsiParser {
	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT"));
	
	@Inject 
	private LatteCSSGrammarAccess grammarAccess;

	@Inject 
	private LatteCSSElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalLatteCSSParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}
	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
