/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLatteCSSValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(io.lattekit.dsl.latteCSS.LatteCSSPackage.eINSTANCE);
		return result;
	}
	
}
