/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LatteCSSAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("io/lattekit/dsl/parser/antlr/internal/InternalLatteCSS.tokens");
	}
}
