/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import io.lattekit.dsl.services.LatteCSSGrammarAccess;

public class LatteCSSParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LatteCSSGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected io.lattekit.dsl.parser.antlr.internal.InternalLatteCSSParser createParser(XtextTokenStream stream) {
		return new io.lattekit.dsl.parser.antlr.internal.InternalLatteCSSParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CSS";
	}
	
	public LatteCSSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LatteCSSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
