/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LatteCSSStandaloneSetup extends LatteCSSStandaloneSetupGenerated {

	def static void doSetup() {
		new LatteCSSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
