/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class LatteCSSIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new LatteCSSStandaloneSetupIdea().createInjector
	}

}
