/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class LatteCSSIdeaModule extends AbstractLatteCSSIdeaModule {
}
