/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang


class LatteCSSFileType extends AbstractLatteCSSFileType {
	public static final LatteCSSFileType INSTANCE = new LatteCSSFileType()
	
	new() {
		super(LatteCSSLanguage.INSTANCE)
	}
}
