/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.lang.pom;

import io.lattekit.dsl.idea.lang.LatteCSSLanguage;
import org.eclipse.xtext.idea.pom.AbstractXtextPomDeclarationSearcher;

public class LatteCSSPomDeclarationSearcher extends AbstractXtextPomDeclarationSearcher {
	public LatteCSSPomDeclarationSearcher() {
		super(LatteCSSLanguage.INSTANCE);
	}
}
