/*
 * generated by Xtext
 */
package io.lattekit.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LatteCSSRuntimeModule extends io.lattekit.dsl.AbstractLatteCSSRuntimeModule {

}
