/*
 * generated by Xtext
 */
package io.lattekit.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LatteCSSStandaloneSetup extends LatteCSSStandaloneSetupGenerated{

	public static void doSetup() {
		new LatteCSSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

