/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractLatteCSSCompletionContributor extends TerminalsCompletionContributor {
	public AbstractLatteCSSCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
