/*
 * generated by Xtext
 */
package io.lattekit.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LatteCSSUiModule extends io.lattekit.dsl.ui.AbstractLatteCSSUiModule {
	public LatteCSSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
