/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;

@SuppressWarnings("all")
public class LatteCSSStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new LatteCSSRuntimeModule());
	}
	
	public void register(Injector injector) {
		
		
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.lattekit.io/dsl/LatteCSS")) {
		EPackage.Registry.INSTANCE.put("http://www.lattekit.io/dsl/LatteCSS", io.lattekit.dsl.latteCSS.LatteCSSPackage.eINSTANCE);
		}
		
		
		org.eclipse.xtext.resource.IResourceFactory resourceFactory = injector.getInstance(org.eclipse.xtext.resource.IResourceFactory.class);
		org.eclipse.xtext.resource.IResourceServiceProvider serviceProvider = injector.getInstance(org.eclipse.xtext.resource.IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("css", resourceFactory);
		org.eclipse.xtext.resource.IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("css", serviceProvider);
		
	}
}
