/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import io.lattekit.dsl.idea.lang.LatteCSSLanguage;

public class LatteCSSExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return LatteCSSLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
