/*
 * generated by Xtext 2.9.0.beta5
 */
package io.lattekit.dsl.idea.completion

import io.lattekit.dsl.idea.lang.LatteCSSLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class LatteCSSCompletionContributor extends AbstractLatteCSSCompletionContributor {
	new() {
		this(LatteCSSLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
